### ISSUE TITLE
broken layout in settings

### ISSUE THREAD

**Issue by blendi-93** [Elundris/Air-Classic#2]
there are some broken margins/paddings in settings > Interface
![broken Settings](http://i.imgur.com/4vq7Kav.png)

using version 2015-0401

**Comment by Elundris** [comment]
Classic is only officially supported on Windows, sadly. It's a large undertaking to make a skin compatible with multiple OS's and I don't plan on making any more substantial updates to Classic (aside from keeping it working with the latest updates).

I will be making a push to get the new Air working on OSX/Linux as my next goal though.
