### ISSUE TITLE
Downloads page after Steam update

### ISSUE THREAD

**Issue by sebie** [Elundris/Air-Classic#3]
I am reporting this mostly just to this (older) version of Air up-to-date with the major additions to the Steam client. I understand if you want to leave it as is to encourage people to move to the new skin (just as I should).

Commit to the new Air, fixing this: [[link]](https://github.com/Elundris/Air-for-Steam/commit/09b1f712303fe7b46564fb5b28e86e4856cca03a)

And the issue in Air-for-Steam refrencing this: [[link]](https://github.com/Elundris/Air-for-Steam/issues/61)

![bug](https://cloud.githubusercontent.com/assets/9204569/8689324/921dc350-2ae9-11e5-896f-cc1bf8a05585.png)

**Comment by Elundris** [comment]
Fear not, I will be fixing this. I just don't want to have two skins to update if Steam changes anything in the beta prior to release.

**Comment by sebie** [comment]
Awesome! :) Even though I will be switching it is nice to see that you still care for the old Air skin.

**Comment by sebie** [comment]
:+1: :)
