### ISSUE TITLE
SteamVR button bug in Steam Beta

### ISSUE THREAD

**Issue by KraXarN** [Elundris/Air-Classic#4]
When using Steam Beta, the button to activate SteamVR becomes bugged
As shown here:
http://i.imgur.com/LC03BS4.png

**Comment by Elundris** [comment]
I've been trying to replicate this new button but it doesn't show up on my Steam. Did you have to do anything other than opt in to the current Steam beta? Is there another group I need to be in, or have some kind of VR hardware maybe?

**Comment by KraXarN** [comment]
I've been using the Steam Beta for a while and only recently showed up.
I do not own any type of VR hardware.
I do run Linux though, I don't know if that has to do with anything...

**Comment by Elundris** [comment]
Ah, I think that's the difference. I'll look into it and see what I can find, stay tuned.
