### ISSUE TITLE
Add Phone Number Notification Doesn't Display Properly

### ISSUE THREAD

**Issue by DeedleFake** [Elundris/Air-Classic#5]
When a phone number has not been associated with an account, Steam will show a special notification asking the user to add one. This does not display properly in Air-Classic, instead showing up as a malformed, green box that covers up the back button.

How it looks in the default skin:
![add-phone-number](https://cloud.githubusercontent.com/assets/326750/10428764/c4b06d9a-70c1-11e5-9f1f-3250597f4bba.PNG)

How it looks in Air-Classic:
![air-classic-error](https://cloud.githubusercontent.com/assets/326750/10428706/4bdebbce-70c1-11e5-9d4c-1fdf5b11b93a.png)

**Comment by Elundris** [comment]
Fixed today in d905e4d03ff4c689c30dce8da5b55b01546b8840
